[versions]
micronaut-gradle-plugin = "4.6.2"
protobuf-gradle-plugin = "0.10.0"
protobuf = "4.36.1"
junit = "5.14.4"
junit-platform = "1.14.4"
testcontainers = "2.0.5"
archunit = "1.5.0"
jacoco = "0.8.15"
spotbugs-gradle-plugin = "6.5.11"
jsoup = "1.23.2"
dependency-analysis-gradle-plugin = "3.19.1"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }

[plugins]
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-gradle-plugin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis-gradle-plugin" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-gradle-plugin" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronaut-gradle-plugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }
